site_name: Adaptivetheme 8.x Docs
pages:
- Home: index.md
- Installation: 'install.md'
- Theme Generator: 'theme-generator.md'
- Extensions:
  - 'Overview': 'ext/overview.md'
  - 'Responsive menus': 'ext/responsive-menus.md'
  - 'Fonts': 'ext/fonts.md'
#    - 'Title styles': 'ext/title-styles.md'
#    - 'Image alignment and captions': 'ext/image-alignment-captions.md'
#    - 'Touch icons': 'ext/touch-icons.md'
#    - 'Shortcode CSS': 'ext/shortcodes.md'
#    - 'Mobile blocks': 'ext/mobile-blocks.md'
#    - 'Slideshows': 'ext/slideshows.md'
  - 'Custom CSS': 'ext/custom-css.md'
  - 'CKEditor skins': 'ext/ckeditor.md'
#    - 'Markup overrides': 'ext/markup-overrides.md'
#    - 'Developer tools': 'ext/devel-tools.md'
#    - 'Legacy browsers': 'ext/legacy-browsers.md'
- Layout settings:
  - 'Overview': 'layout/overview.md'
  - 'Setting layouts': 'layout/setting-layouts.md'
  - 'Breakpoints': 'layout/breakpoints.md'
  - 'Adding new regions': 'layout/new-regions.md'
  - 'Template suggestions': 'layout/template-suggestions.md'
  - 'Max width overrides': 'layout/max-width.md'
  - 'Backups': 'layout/backups.md'
- Building Themes:
  - 'Introduction': 'theming/theming.md'
  - 'Extensions vs Manual coding': 'theming/extensions-vs-code.md'
  - 'CSS or SCSS?': 'theming/css-vs-scss.md'
  - 'UIKit': 'theming/uikit.md'
  - 'Libraries': 'theming/libraries.md'
  - 'Locating SCSS Styles': 'theming/locating-scss.md'
  - 'Adding Components': 'theming/new-components.md'
  - 'Templates': 'theming/templates.md'
  - 'Breakpoints & Media Queries': 'theming/breakpoints.md'
  - 'Layout': 'theming/layout.md'
  - 'Color Module': 'theming/color-module.md'
  - 'Font Awesome': 'theming/font-awesome.md'
- Sub-sub Skin Themes:
  - 'Introduction': 'theming/skins/skin-theming.md'
  - 'Generating Skin Themes': 'theming/skins/generate.md'
  - 'File Structure': 'theming/skins/file-structure.md'
  - 'Inheritance': 'theming/skins/inheritance.md'
theme: readthedocs
docs_dir: docs
